// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ekfgfyjtfgjrfwbkoifd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVrZmdmeWp0ZmdqcmZ3YmtvaWZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU5NzQzNjUsImV4cCI6MjA2MTU1MDM2NX0.BuOzE--PTtOKdbyqptQgrCh1ChvHjgls4JiIAUXMDMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);